[project]
name = "neuroevosim"
version = "0.1.0"
description = "Evolving artificial creatures in a simulated world"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]
